/*
===============================================================================
 03_rfm_analysis.sql
-------------------------------------------------------------------------------
 Purpose : Customer segmentation using RFM (Recency, Frequency, Monetary)
           analysis. Only rows with a known customer_id are used (see
           01_data_cleaning.sql — guest/unidentified checkouts are excluded
           from customer-level analysis).

 Method:
   Recency  = days between the customer's last purchase and the day after
              the dataset's last recorded transaction (the "analysis date").
   Frequency= number of distinct invoices placed by the customer.
   Monetary = total revenue generated by the customer.

   Each metric is scored 1-5 using NTILE(5) quintiles (5 = best).
   Recency is scored in reverse (a LOWER recency, i.e. more recent, gets
   a HIGHER score).

 Segment rules (applied to the 1-5 R/F/M scores):
   VIP             : R >= 4 AND F >= 4 AND M >= 4   (recent, frequent, high spend)
   Frequent Buyer   : F >= 4 AND NOT VIP              (buys often, lower spend/recency)
   Active           : R >= 4 AND F < 4                (recent but not yet frequent)
   At Risk          : R <= 2 AND (F >= 3 OR M >= 3)   (used to be valuable, gone quiet)
   Regular          : everything else (default bucket)

 Output table: customer_rfm
===============================================================================
*/

DROP TABLE IF EXISTS customer_rfm;

CREATE TABLE customer_rfm AS
WITH analysis_date AS (
    SELECT DATE(MAX(invoice_date), '+1 day') AS ref_date
    FROM transactions_enriched
),
customer_agg AS (
    SELECT
        t.customer_id,
        CAST(JULIANDAY((SELECT ref_date FROM analysis_date)) - JULIANDAY(MAX(t.invoice_date)) AS INTEGER) AS recency_days,
        COUNT(DISTINCT t.invoice_no)   AS frequency,
        ROUND(SUM(t.total_price), 2)   AS monetary
    FROM transactions_enriched t
    WHERE t.customer_id IS NOT NULL
    GROUP BY t.customer_id
),
scored AS (
    SELECT
        customer_id,
        recency_days,
        frequency,
        monetary,
        -- reverse-scored: more recent (lower days) => higher score
        (6 - NTILE(5) OVER (ORDER BY recency_days ASC)) AS recency_score,
        NTILE(5) OVER (ORDER BY frequency ASC)          AS frequency_score,
        NTILE(5) OVER (ORDER BY monetary ASC)           AS monetary_score
    FROM customer_agg
)
SELECT
    customer_id,
    recency_days,
    frequency,
    monetary,
    recency_score,
    frequency_score,
    monetary_score,
    (recency_score + frequency_score + monetary_score) AS rfm_total_score,
    CASE
        WHEN recency_score >= 4 AND frequency_score >= 4 AND monetary_score >= 4 THEN 'VIP'
        WHEN frequency_score >= 4                                              THEN 'Frequent Buyer'
        WHEN recency_score >= 4 AND frequency_score < 4                        THEN 'Active'
        WHEN recency_score <= 2 AND (frequency_score >= 3 OR monetary_score >= 3) THEN 'At Risk'
        ELSE 'Regular'
    END AS customer_segment
FROM scored;

-- Sanity check: segment sizes should roughly resemble a typical customer base
SELECT customer_segment, COUNT(*) AS num_customers, ROUND(SUM(monetary),2) AS segment_revenue
FROM customer_rfm
GROUP BY customer_segment
ORDER BY segment_revenue DESC;
